### ISSUE TITLE
API URL settings being ignored in .env file.

### ISSUE THREAD

**Issue by Hercules2048** [revoltchat/self-hosted#24]
Description :
Changing the URL/port to the API server in the .env file does not seem to do anything. After restarting the host machine and the docker, the changes are not honored and instead revolt wants to connect to the API server at example.com:8000.

This is especially apparent when you attempt to use a HTTPS reverse proxy using caddy or nginx, as you can't really get around this.
![2021-12-21 08_23_19-Untitled - Paint](https://user-images.githubusercontent.com/96486547/146957739-a4ba3a60-80d0-4f65-b25f-15d4242fca4c.png)
![2021-12-21 08_43_29-Untitled - Paint](https://user-images.githubusercontent.com/96486547/146957761-b1c09a12-5d53-43fa-994c-5289d9189767.png)

**Comment by jim3692** [comment]
I don't know if it's related, but I just updated Revolt and it tries to login using the official API instead of mine

**Comment by insertish** [comment]
I think we may have solved this in chat, anyways for anyone else, some common issues include:
- Editing `.env` instead of `docker-compose.yml` for port changes.
- Not specifying public URL in `.env`.
- Not running `docker-compose up -d` to push everything to the Docker daemon.

> I don't know if it's related, but I just updated Revolt and it tries to login using the official API instead of mine

Sounds unrelated, open an issue about it if you have more information.
