### ISSUE TITLE
bug: Can Sign Up Unknown Error

### ISSUE THREAD

**Issue by s8rr** [revoltchat/self-hosted#93]
### What happened?

I installed the Revolt Chat using the Docs given. after installation when i try to sign up i got this error.
![image](https://github.com/user-attachments/assets/d1d9baef-e05b-4ad9-90a4-d4a0c7496639)
![image](https://github.com/user-attachments/assets/ce842157-6562-44c4-be09-0ca12b4bcc4a)

**Comment by IAmTomahawkx** [comment]
youve sent pictures of the login screen. Are you attempting to log in or sign up? Please provide more detail, as well as the error returned by the API from the network console.

**Comment by s8rr** [comment]
In the sign up i get this error.

**Comment by paboum** [comment]
While debugging the same issue in chrome I get an error:
`Mixed Content: The page at 'https://revolt.my.domain/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://local.revolt.chat/ws'. This request has been blocked; this endpoint must be available over WSS.`
After some investigation I've found out that the only place setting the incorrect url could be `Revolt.toml` which by default is initialized with unusable value rather than what comes from `.env` file which is ignored silently.

**Comment by paboum** [comment]
I maned to work around via:
1. Set up `.env` by:
    * Replacing all occurences `://local.revolt.chat` with `s://my.domain`
    * In `HOSTNAME`, however, removing `https://` prefix
2. Create `Revolt.toml` file with correct `app`, `api`, `events`, `autumn` and `january` settings.
3. Editing `docker-compose.yml` by adding:
```
     volumes:
      - ./Revolt.toml:/Revolt.toml
```

in `services.api` and `services.events` sections.

Another prudent thing to do would also be checking if config isn't missing critical values like this (treating `local.revolt.chat` as an erroreous) and yielding a warning or even preventing a container from starting.

**Comment by OlesyaShell** [comment]
When enabled https - in source code you have hardcoded http://_custom_doman/api/
For debug - setup https, open dev tools in browser.
Its reason why created new account and other operations impossible.

**Comment by OlesyaShell** [comment]
++ also hardcoded http://_custom_domain/api/auth/account/create

**Comment by insertish** [comment]
Stale issue, OP has not followed up.

**Comment by paboum** [comment]
> Stale issue, OP has not followed up.

Dead project, issue reported but not fixed, will never use this fork again.
